data = {
	"aku": ["saya", "aku", "ane", "aing", "kulo", "gue", "gua"],
	"kamu": ["kamu", "lo", "anda", "sampean", "kon", "koe", "kowe", "lu"],
	"dia" : ["dia", "ia"],
	"kita" : ["kita","dewek"],
	"kami": ['kami'],
	"mereka": ["mereka",'ia'],
	"apa": ["apa", "apakah",'opo'],
	"bagaimana": ["bagaimana", "bagaimanakah",'gimana'],
	"kapan":["kapan", "kapankah"],
	"dimana": ["dimana", "di mana", "di manakah"],
	"kenapa": ["kenapa", "mengapa"],
	"siapa": ["siapa", "siapakah"],
    "berapa": ["berapa", "pinten", "piro"],
	"laki-laki": ["laki-laki", "pria", "cowok"],
	"pacar": ["pacar",'kekasih'],
	"perempuan": ["perempuan", "cewek", "wanita"],
	"teman": ["teman", "temen"],
    "makan": ["makan", "nedho", "dhahar", "maem"],
    "minum": ["minum"],
    "belajar": ["belajar", "sinau", "maos"],
    "pergi": ["pergi", "berangkat", "lungo"],
    "halo": ["halo", "hai", "hallo"],
    "kabar": ["kabar"],
    "baik": ["baik", "bagus"],
    "terimakasih": ["terima kasih", "terimakasih", "makasih", "suwun", "nuwun", "mantur suwun", "mantur nuwun"],
    "sama-sama": ["samasama", "sama sama", "sami sami", "podo podo"],
    "suka": ["suka", "seneng"],
    "sekolah": ["sekolah", "kampus"],
    "kelas": ["kelas"],
    "rumah": ["rumah", "omah"],
    }
